<?php

namespace AppBundle\Entity;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * FortuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FortuneRepository extends \Doctrine\ORM\EntityRepository
{
  public function findLast()
  {
    $queryBuilder = $this->createQueryBuilder('f')
      ->orderBy("f.createAt", "DESC");
      return new DoctrineORMAdapter($queryBuilder);
  }

  public function findByAuthor($author)
  {
    return $this->createQueryBuilder('f')
    ->where("f.author = :author")
    ->setParameter("author", $author)
    ->getQuery()
    ->getResult();
  }

  public function findByStory($id)
  {
      return $this->createQueryBuilder('f')
      ->where("f.id = :id")
      ->setParameter("id", $id)
      ->getQuery()
      ->getResult();
  }

  public function bestRated()
  {
    return $this->createQueryBuilder('f')
    ->orderBy("f.upVote - f.downVote", "DESC")
    ->getQuery()
    ->getResult();
  }

  public function worstRated()
  {
    return $this->createQueryBuilder('f')
    ->orderBy("f.upVote - f.downVote", "ASC")
    ->getQuery()
    ->getResult();
  }
}
